objs :=	alloc.o basic-block.o bytecode-arithmetic-converters.o \
	bytecode-cfg-builder.o bytecodes.o bytecode-to-ir.o \
	compilation-unit.o expression.o insn-selector.o instruction.o jit.o \
	jit-compiler.o stack.o statement.o x86-objcode.o
