objs :=	alloc.o basic-block.o arithmetic-bc.o \
	bytecode-cfg-builder.o bytecodes.o bytecode-to-ir.o \
	compilation-unit.o expression.o insn-selector.o instruction.o jit.o \
	jit-compiler.o jvm_types.o load-store-bc.o object-bc.o ostack-bc.o \
	statement.o tree-printer.o typeconv-bc.o x86-objcode.o
