#!/bin/sh

GNU_CLASSPATH_ROOT=`./tools/classpath-config`
if test x"$GNU_CLASSPATH_ROOT" = x -o ! -d $GNU_CLASSPATH_ROOT; then
  echo "Error! Cannot find GNU Classpath installed."
  exit
fi

GLIBJ=$GNU_CLASSPATH_ROOT/share/classpath/glibj.zip
BOOTCLASSPATH=lib/classes.zip:$GLIBJ

./jato -Dgnu.classpath.boot.library.path=$GNU_CLASSPATH_ROOT/lib/classpath -Xbootclasspath:$BOOTCLASSPATH $*
