objs :=	access.o alloc.o cast.o class.o direct.o dll.o dll_ffi.o excep.o \
	execute.o frame.o hash.o interp.o jam.o jni.o lock.o natives.o \
	os/linux/dll_os.o os/linux/i386/dll_md.o os/linux/i386/init.o \
	properties.o reflect.o resolve.o string.o thread.o utf8.o zip.o
